AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Forstume-app

  Nested stack server-less micro-service architecture.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BlogNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: blog/template.yaml

  AuthenticationNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: authentication/template.yaml
