AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Forstume-app

  Nested stack server-less micro-service architecture.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AuthenticationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: authentication
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        Authentication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AuthenticationApi:
    Description: "API Gateway endpoint URL for Prod stage for Authentication function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AuthenticationFunction:
    Description: "Authentication Lambda Function ARN"
    Value: !GetAtt AuthenticationFunction.Arn
  AuthenticationFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AuthenticationFunctionRole.Arn
