AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Blog-app

  Blog is a child stack handles request of blog: create, update, delete and retrieve blog.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BlogFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: blog
      Handler: blogs.lambda_handler
      Runtime: python3.6
      Events:
        Authentication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /blogs
            Method: get

  CategoriesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: blog
      Handler: categories.lambda_handler
      Runtime: python3.6
      Events:
        Authentication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /categories
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BlogApi:
    Description: "API Gateway endpoint URL for Prod stage for Blog function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BlogFunction:
    Description: "Blog Lambda Function ARN"
    Value: !GetAtt BlogFunction.Arn
  BlogFunctionIamRole:
    Description: "Implicit IAM Role created for Blog function"
    Value: !GetAtt BlogFunctionRole.Arn

  CategoriesApi:
    Description: "API Gateway endpoint URL for Prod stage for Categories function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CategoriesFunction:
    Description: "Categories Lambda Function ARN"
    Value: !GetAtt CategoriesFunction.Arn
  CategoriesFunctionIamRole:
    Description: "Implicit IAM Role created for Categories function"
    Value: !GetAtt CategoriesFunctionRole.Arn
